kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

node:
  cloud: tencent
  location: hongkong

volumes:
  - name: cache
    host:
      path: /var/docker/drone-runner/cache/gomod


steps:
  - name: build
    image: golang:alpine
    volumes:
      - name: cache
        path: /go/pkg/mod
    commands:
      - apk update && apk add --no-cache git build-base tzdata
      - go mod download
      - go build -o onefile

  - name: docker-build-push
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      repo:  cloverzrg/onefile
      tags: latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password

  - name: ssh-deploy
    image: appleboy/drone-ssh
    when:
      branch:
        - master
    settings:
      host:
        from_secret: deploy_host
      username: root
      port: 22
      key:
        from_secret: ssh_key
      script:
        - cd /var/docker/onefile
        - echo "pulling image"
        - docker-compose pull -q
        - docker-compose down && docker-compose up -d
        - sleep 5
        - docker-compose logs --tail=200